 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: armagedon                                                   
     # Surfaces =   5
     # Strips   = 200
     # Vortices =3000

  Sref = 0.25740       Cref = 0.19500       Bref =  1.3200    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02345     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.18400     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.18470
  CDtot =   0.01701
  CDvis =   0.01425     CDind = 0.0027648
  CLff  =   0.18461     CDff  = 0.0010207    | Trefftz
  CYff  =   0.00000         e =    1.5701    | Plane  

   aileron         =   0.00003
   profundor       =  -0.87445

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.196712    CLb =  -0.000000
 y  force CY |    CYa =   0.000001    CYb =  -0.146026
 x' mom.  Cl'|    Cla =  -0.000002    Clb =  -0.015072
 y  mom.  Cm |    Cma =  -2.479769    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000001    Cnb =   0.069705

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =  12.644018    CLr =  -0.000001
 y  force CY |    CYp =   0.023781    CYq =   0.000003    CYr =   0.153096
 x' mom.  Cl'|    Clp =  -0.510966    Clq =  -0.000001    Clr =   0.064885
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -19.544716    Cmr =   0.000001
 z' mom.  Cn'|    Cnp =  -0.019375    Cnq =  -0.000002    Cnr =  -0.082545

                  aileron      d01     profundor    d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.008237
 y  force CY |   CYd01 =   0.000179   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.006704   Cld02 =  -0.000000
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028921
 z' mom.  Cn'|   Cnd01 =   0.000020   Cnd02 =  -0.000000
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000094
 span eff.   |    ed01 =  -0.000006    ed02 =  -0.003895



 Neutral point  Xnp =   0.093050

 Clb Cnr / Clr Cnb  =   0.275083    (  > 1 if spirally stable )
