 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: test_plane                                                  
     # Surfaces =   4
     # Strips   = 160
     # Vortices =2400

  Sref = 0.60000       Cref = 0.30000       Bref =  2.0000    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =   0.00000     p'b/2V =   0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.03811     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =   0.32122     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =  -0.31970
  CDtot =   0.04930
  CDvis =   0.04741     CDind = 0.0018908
  CLff  =  -0.31976     CDff  =-0.0070799    | Trefftz
  CYff  =   0.00000         e =   -0.6896    | Plane  

   aileron         =  -0.00000
   profundor       =   6.62969

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =  11.383851    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.047427
 x' mom.  Cl'|    Cla =  -0.000000    Clb =   0.046151
 y  mom.  Cm |    Cma =  -4.083255    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.003631

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =  21.647983    CLr =  -0.000000
 y  force CY |    CYp =  -0.099971    CYq =   0.000000    CYr =   0.000410
 x' mom.  Cl'|    Clp =  -5.125023    Clq =   0.000000    Clr =  -0.386211
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -13.934072    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =   0.075312    Cnq =   0.000000    Cnr =  -0.037097

                  aileron      d01     profundor    d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011736
 y  force CY |   CYd01 =   0.000016   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.014627   Cld02 =  -0.000000
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.021467
 z' mom.  Cn'|   Cnd01 =   0.000007   Cnd02 =   0.000000
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.001775
 span eff.   |    ed01 =  -0.000000    ed02 =   0.223466



 Neutral point  Xnp =   0.107607

 Clb Cnr / Clr Cnb  =   1.221029    (  > 1 if spirally stable )
