 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: armagedon                                                   
     # Surfaces =   2
     # Strips   =  80
     # Vortices =1200

  Sref = 0.62500       Cref = 0.25000       Bref =  2.5000    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.02746     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.17222     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.46132
  CZtot =  -0.44688     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.46459
  CDtot =   0.11625
  CDvis =   0.10847     CDind = 0.0077792
  CLff  =   0.46363     CDff  = 0.0078380    | Trefftz
  CYff  =   0.00000         e =    0.8730    | Plane  

   aileron         =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.592778    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.108474
 x' mom.  Cl'|    Cla =  -0.000000    Clb =   0.000117
 y  mom.  Cm |    Cma =  -1.345516    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.002243

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   6.520543    CLr =  -0.000000
 y  force CY |    CYp =  -0.001316    CYq =   0.000000    CYr =   0.004295
 x' mom.  Cl'|    Clp =  -0.590531    Clq =  -0.000000    Clr =   0.138892
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -2.498333    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.054664    Cnq =   0.000000    Cnr =  -0.035871

                  aileron      d01 
                  ----------------
 z' force CL |   CLd01 =   0.000000
 y  force CY |   CYd01 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.006556
 y  mom.  Cm |   Cmd01 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000001
 Trefftz drag| CDffd01 =   0.000000
 span eff.   |    ed01 =  -0.000000



 Neutral point  Xnp =   0.073241

 Clb Cnr / Clr Cnb  =  -0.013461    (  > 1 if spirally stable )
