 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: armagedon                                                   
     # Surfaces =   2
     # Strips   =  80
     # Vortices =1200

  Sref = 0.62500       Cref = 0.25000       Bref =  2.5000    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.31962     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07047     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.62642
  CZtot =  -1.04574     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.04533
  CDtot =   0.07630
  CDvis =   0.03886     CDind = 0.0374385
  CLff  =   1.04554     CDff  = 0.0374391    | Trefftz
  CYff  =   0.00000         e =    0.9294    | Plane  

   aileron         =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.444124    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.038865
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.041911
 y  mom.  Cm |    Cma =  -1.203261    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.000705

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.578563    CLr =  -0.000000
 y  force CY |    CYp =   0.083832    CYq =   0.000000    CYr =   0.000476
 x' mom.  Cl'|    Clp =  -0.557209    Clq =  -0.000000    Clr =   0.295929
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -2.503531    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.096346    Cnq =   0.000000    Cnr =  -0.019569

                  aileron      d01 
                  ----------------
 z' force CL |   CLd01 =   0.000000
 y  force CY |   CYd01 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.006294
 y  mom.  Cm |   Cmd01 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000152
 Trefftz drag| CDffd01 =   0.000000
 span eff.   |    ed01 =  -0.000000



 Neutral point  Xnp =   0.067688

 Clb Cnr / Clr Cnb  =   3.928743    (  > 1 if spirally stable )
