function controlstring = controlstring(controldata)
    controlstring = "CONTROL\n" + controldata.name + " " + ...
        num2str(controldata.gain) + " " + ...
        num2str(controldata.Xhinge) + " 0 0 0 " + ...
        num2str(controldata.sgnDup)+"\n";
end